### ISSUE TITLE
URLEncode for google search

### ISSUE THREAD

**Issue by SBBTD** [horsicq/die_widget#1]
"C/C++" was decoded as C/C[space][space] by browser or google.
This needs a URLEncode.

https://github.com/horsicq/die_widget/blob/dd53b665b1fded1df8def74de987dbcc41653bfc/die_widget.cpp#L314

Sorry to bother you with such a little bug : )

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will take a look
